version: '2'

services:

   web:
    network_mode: "bridge"
    container_name: preslog
    build: ./env/docker/
    restart: always
    external_links:
      - "proxy"
    links:
      - "db:database"
    environment:
      - VIRTUAL_HOST=local.preslog
      # HTTPS does not currently work with the proxy
      - HTTPS_METHOD=noredirect
    extra_hosts:
      - "local.preslog:127.0.0.1"
    volumes:
         - .:/home/preslog

   db:
    network_mode: "bridge"
    ports:
       - "27017:27017"
    image: mongo:3.0
    volumes:
        - ./data:/data/db



